package com.hskflashcard.ui.theme
import androidx.compose.ui.graphics.Color

val primaryLightMediumContrast = Color(0xFF0B3F17)
val onPrimaryLightMediumContrast = Color(0xFFFFFFFF)
val primaryContainerLightMediumContrast = Color(0xFF46784A)
val onPrimaryContainerLightMediumContrast = Color(0xFFFFFFFF)
val secondaryLightMediumContrast = Color(0xFF2A3A2A)
val onSecondaryLightMediumContrast = Color(0xFFFFFFFF)
val secondaryContainerLightMediumContrast = Color(0xFF60725E)
val onSecondaryContainerLightMediumContrast = Color(0xFFFFFFFF)
val tertiaryLightMediumContrast = Color(0xFF083C42)
val onTertiaryLightMediumContrast = Color(0xFFFFFFFF)
val tertiaryContainerLightMediumContrast = Color(0xFF48747B)
val onTertiaryContainerLightMediumContrast = Color(0xFFFFFFFF)
val errorLightMediumContrast = Color(0xFF740006)
val onErrorLightMediumContrast = Color(0xFFFFFFFF)
val errorContainerLightMediumContrast = Color(0xFFCF2C27)
val onErrorContainerLightMediumContrast = Color(0xFFFFFFFF)
val backgroundLightMediumContrast = Color(0xFFF5F5F5)
val onBackgroundLightMediumContrast = Color(0xFF181D18)
val surfaceLightMediumContrast = Color(0xFFFFFFFF)
val onSurfaceLightMediumContrast = Color(0xFF0C1213)
val surfaceVariantLightMediumContrast = Color(0xFFDBE4E6)
val onSurfaceVariantLightMediumContrast = Color(0xFF2F3839)
val outlineLightMediumContrast = Color(0xFF4B5456)
val outlineVariantLightMediumContrast = Color(0xFF656F70)
val scrimLightMediumContrast = Color(0xFF000000)
val inverseSurfaceLightMediumContrast = Color(0xFF2B3133)
val inverseOnSurfaceLightMediumContrast = Color(0xFFECF2F3)
val inversePrimaryLightMediumContrast = Color(0xFF9ED49D)
val surfaceDimLightMediumContrast = Color(0xFFC2C7C9)
val surfaceBrightLightMediumContrast = Color(0xFFF5FAFB)
val surfaceContainerLowestLightMediumContrast = Color(0xFFFFFFFF)
val surfaceContainerLowLightMediumContrast = Color(0xFFEFF5F6)
val surfaceContainerLightMediumContrast = Color(0xFFE3E9EA)
val surfaceContainerHighLightMediumContrast = Color(0xFFD8DEDF)
val surfaceContainerHighestLightMediumContrast = Color(0xFFCDD3D4)

val primaryDarkMediumContrast = Color(0xFFB3EAB2)
val onPrimaryDarkMediumContrast = Color(0xFF002D0C)
val primaryContainerDarkMediumContrast = Color(0xFF699D6B)
val onPrimaryContainerDarkMediumContrast = Color(0xFF000000)
val secondaryDarkMediumContrast = Color(0xFFCEE2CA)
val onSecondaryDarkMediumContrast = Color(0xFF1A291A)
val secondaryContainerDarkMediumContrast = Color(0xFF839681)
val onSecondaryContainerDarkMediumContrast = Color(0xFF000000)
val tertiaryDarkMediumContrast = Color(0xFFB6E4EC)
val onTertiaryDarkMediumContrast = Color(0xFF002A30)
val tertiaryContainerDarkMediumContrast = Color(0xFF6C989F)
val onTertiaryContainerDarkMediumContrast = Color(0xFF000000)
val errorDarkMediumContrast = Color(0xFFFFD2CC)
val onErrorDarkMediumContrast = Color(0xFF540003)
val errorContainerDarkMediumContrast = Color(0xFFFF5449)
val onErrorContainerDarkMediumContrast = Color(0xFF000000)
val backgroundDarkMediumContrast = Color(0xFF121212)
val onBackgroundDarkMediumContrast = Color(0xFFE0E4DB)
val surfaceDarkMediumContrast = Color(0xFF1F1F1F)
val onSurfaceDarkMediumContrast = Color(0xFFFFFFFF)
val surfaceVariantDarkMediumContrast = Color(0xFF3F484A)
val onSurfaceVariantDarkMediumContrast = Color(0xFFD4DEE0)
val outlineDarkMediumContrast = Color(0xFFAAB4B5)
val outlineVariantDarkMediumContrast = Color(0xFF889294)
val scrimDarkMediumContrast = Color(0xFF000000)
val inverseSurfaceDarkMediumContrast = Color(0xFFDEE3E5)
val inverseOnSurfaceDarkMediumContrast = Color(0xFF252B2C)
val inversePrimaryDarkMediumContrast = Color(0xFF205228)
val surfaceDimDarkMediumContrast = Color(0xFF1F1F1F)
val surfaceBrightDarkMediumContrast = Color(0xFF3F4647)
val surfaceContainerLowestDarkMediumContrast = Color(0xFF040809)
val surfaceContainerLowDarkMediumContrast = Color(0xFF191F20)
val surfaceContainerDarkMediumContrast = Color(0xFF23292A)
val surfaceContainerHighDarkMediumContrast = Color(0xFF2D3435)
val surfaceContainerHighestDarkMediumContrast = Color(0xFF393F40)







